import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header_of_full_website from "@/components/layout/Header_of_full_website";
import { Footer } from "@/components/sections/footer";
// ----------------------------------


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="flex flex-col tracking-wide items-center">
        <Header_of_full_website></Header_of_full_website>

        <main className="w-full 2xl:container">
          {children}
        </main>


        <Footer></Footer>

      </body>
    </html>
  );
}
