const fs = require('fs')
const path = require('path')

// Read existing all_india_cities to map districts to states
const citiesData = JSON.parse(
  fs.readFileSync(path.join(__dirname, '../src/data/all_india_cities.json'), 'utf8')
)

// Pre-defined prominent villages, talukas, sub-districts and rural areas across Indian states
const VILLAGES_DATA = [
  // ==========================================
  // GUJARAT (Comprehensive coverage)
  // ==========================================
  // Ahmedabad
  { name: 'Ghatlodia', district: 'Ahmedabad', state: 'Gujarat' },
  { name: 'Chandlodiya', district: 'Ahmedabad', state: 'Gujarat' },
  { name: 'Sola', district: 'Ahmedabad', state: 'Gujarat' },
  { name: 'Ranip', district: 'Ahmedabad', state: 'Gujarat' },
  { name: 'New Ranip', district: 'Ahmedabad', state: 'Gujarat' },
  { name: 'Naranpura', district: 'Ahmedabad', state: 'Gujarat' },
  { name: 'Memnagar', district: 'Ahmedabad', state: 'Gujarat' },
  { name: 'Thaltej', district: 'Ahmedabad', state: 'Gujarat' },
  { name: 'Bopal', district: 'Ahmedabad', state: 'Gujarat' },
  { name: 'South Bopal', district: 'Ahmedabad', state: 'Gujarat' },
  { name: 'Gota', district: 'Ahmedabad', state: 'Gujarat' },
  { name: 'Satellite', district: 'Ahmedabad', state: 'Gujarat' },
  { name: 'Bodakdev', district: 'Ahmedabad', state: 'Gujarat' },
  { name: 'Vastrapur', district: 'Ahmedabad', state: 'Gujarat' },
  { name: 'Navrangpura', district: 'Ahmedabad', state: 'Gujarat' },
  { name: 'Paldi', district: 'Ahmedabad', state: 'Gujarat' },
  { name: 'Maninagar', district: 'Ahmedabad', state: 'Gujarat' },
  { name: 'Sabarmati', district: 'Ahmedabad', state: 'Gujarat' },
  { name: 'Motera', district: 'Ahmedabad', state: 'Gujarat' },
  { name: 'Chandkheda', district: 'Ahmedabad', state: 'Gujarat' },
  { name: 'Science City', district: 'Ahmedabad', state: 'Gujarat' },
  { name: 'Chanakyapuri', district: 'Ahmedabad', state: 'Gujarat' },
  { name: 'Nirnay Nagar', district: 'Ahmedabad', state: 'Gujarat' },
  { name: 'Akhbarnagar', district: 'Ahmedabad', state: 'Gujarat' },
  { name: 'Shilaj', district: 'Ahmedabad', state: 'Gujarat' },
  { name: 'Shela', district: 'Ahmedabad', state: 'Gujarat' },
  { name: 'Tragad', district: 'Ahmedabad', state: 'Gujarat' },
  { name: 'Chenpur', district: 'Ahmedabad', state: 'Gujarat' },
  { name: 'Usmanpura', district: 'Ahmedabad', state: 'Gujarat' },
  { name: 'Ambawadi', district: 'Ahmedabad', state: 'Gujarat' },
  { name: 'Ashram Road', district: 'Ahmedabad', state: 'Gujarat' },
  { name: 'Ellisbridge', district: 'Ahmedabad', state: 'Gujarat' },
  { name: 'Shahibaug', district: 'Ahmedabad', state: 'Gujarat' },
  { name: 'Isanpur', district: 'Ahmedabad', state: 'Gujarat' },
  { name: 'Ghodasar', district: 'Ahmedabad', state: 'Gujarat' },
  { name: 'Vatva', district: 'Ahmedabad', state: 'Gujarat' },
  { name: 'Narol', district: 'Ahmedabad', state: 'Gujarat' },
  { name: 'Naroda', district: 'Ahmedabad', state: 'Gujarat' },
  { name: 'Nikol', district: 'Ahmedabad', state: 'Gujarat' },
  { name: 'Odhav', district: 'Ahmedabad', state: 'Gujarat' },
  { name: 'Vastral', district: 'Ahmedabad', state: 'Gujarat' },
  { name: 'Singarva', district: 'Ahmedabad', state: 'Gujarat' },
  { name: 'Kathwada', district: 'Ahmedabad', state: 'Gujarat' },
  { name: 'Jodhpur', district: 'Ahmedabad', state: 'Gujarat' },
  { name: 'Sarkhej', district: 'Ahmedabad', state: 'Gujarat' },
  { name: 'Makarba', district: 'Ahmedabad', state: 'Gujarat' },
  { name: 'Vejalpur', district: 'Ahmedabad', state: 'Gujarat' },
  { name: 'Vasna', district: 'Ahmedabad', state: 'Gujarat' },
  { name: 'Sanand', district: 'Ahmedabad', state: 'Gujarat' },
  { name: 'Bavla', district: 'Ahmedabad', state: 'Gujarat' },
  { name: 'Dholka', district: 'Ahmedabad', state: 'Gujarat' },
  { name: 'Viramgam', district: 'Ahmedabad', state: 'Gujarat' },
  { name: 'Bareja', district: 'Ahmedabad', state: 'Gujarat' },
  { name: 'Mandal', district: 'Ahmedabad', state: 'Gujarat' },
  { name: 'Detroj', district: 'Ahmedabad', state: 'Gujarat' },
  { name: 'Dhandhuka', district: 'Ahmedabad', state: 'Gujarat' },
  { name: 'Dholera', district: 'Ahmedabad', state: 'Gujarat' },

  // Gandhinagar
  { name: 'Sector 1-30 Gandhinagar', district: 'Gandhinagar', state: 'Gujarat' },
  { name: 'Koba', district: 'Gandhinagar', state: 'Gujarat' },
  { name: 'Kudasan', district: 'Gandhinagar', state: 'Gujarat' },
  { name: 'Raysan', district: 'Gandhinagar', state: 'Gujarat' },
  { name: 'Sargasan', district: 'Gandhinagar', state: 'Gujarat' },
  { name: 'Zundal', district: 'Gandhinagar', state: 'Gujarat' },
  { name: 'Chiloda', district: 'Gandhinagar', state: 'Gujarat' },
  { name: 'Pethapur', district: 'Gandhinagar', state: 'Gujarat' },
  { name: 'Mansa', district: 'Gandhinagar', state: 'Gujarat' },
  { name: 'Kalol', district: 'Gandhinagar', state: 'Gujarat' },
  { name: 'Dehgam', district: 'Gandhinagar', state: 'Gujarat' },

  // Surat
  { name: 'Adajan', district: 'Surat', state: 'Gujarat' },
  { name: 'Varachha', district: 'Surat', state: 'Gujarat' },
  { name: 'Katargam', district: 'Surat', state: 'Gujarat' },
  { name: 'Althan', district: 'Surat', state: 'Gujarat' },
  { name: 'Vesu', district: 'Surat', state: 'Gujarat' },
  { name: 'Pal', district: 'Surat', state: 'Gujarat' },
  { name: 'Kapodra', district: 'Surat', state: 'Gujarat' },
  { name: 'Udhna', district: 'Surat', state: 'Gujarat' },
  { name: 'Rander', district: 'Surat', state: 'Gujarat' },
  { name: 'Piplod', district: 'Surat', state: 'Gujarat' },
  { name: 'Bardoli', district: 'Surat', state: 'Gujarat' },
  { name: 'Kamrej', district: 'Surat', state: 'Gujarat' },
  { name: 'Olpad', district: 'Surat', state: 'Gujarat' },
  { name: 'Mandvi (Surat)', district: 'Surat', state: 'Gujarat' },
  { name: 'Mahuva (Surat)', district: 'Surat', state: 'Gujarat' },

  // Vadodara
  { name: 'Alkapuri', district: 'Vadodara', state: 'Gujarat' },
  { name: 'Manjalpur', district: 'Vadodara', state: 'Gujarat' },
  { name: 'Sayajigunj', district: 'Vadodara', state: 'Gujarat' },
  { name: 'Karelibaug', district: 'Vadodara', state: 'Gujarat' },
  { name: 'Gotri', district: 'Vadodara', state: 'Gujarat' },
  { name: 'Waghodia Road', district: 'Vadodara', state: 'Gujarat' },
  { name: 'Akota', district: 'Vadodara', state: 'Gujarat' },
  { name: 'Padra', district: 'Vadodara', state: 'Gujarat' },
  { name: 'Karjan', district: 'Vadodara', state: 'Gujarat' },
  { name: 'Savli', district: 'Vadodara', state: 'Gujarat' },
  { name: 'Dabhoi', district: 'Vadodara', state: 'Gujarat' },

  // Rajkot
  { name: 'Kalawad Road', district: 'Rajkot', state: 'Gujarat' },
  { name: 'Yagnik Road', district: 'Rajkot', state: 'Gujarat' },
  { name: 'University Road', district: 'Rajkot', state: 'Gujarat' },
  { name: 'Mavdi', district: 'Rajkot', state: 'Gujarat' },
  { name: 'Gondal', district: 'Rajkot', state: 'Gujarat' },
  { name: 'Jetpur', district: 'Rajkot', state: 'Gujarat' },
  { name: 'Dhoraji', district: 'Rajkot', state: 'Gujarat' },
  { name: 'Upleta', district: 'Rajkot', state: 'Gujarat' },
  { name: 'Jasdan', district: 'Rajkot', state: 'Gujarat' },
  { name: 'Kotda Sangani', district: 'Rajkot', state: 'Gujarat' },

  // Banaskantha (Palanpur)
  { name: 'Palanpur City', district: 'Banaskantha', state: 'Gujarat' },
  { name: 'Deesa', district: 'Banaskantha', state: 'Gujarat' },
  { name: 'Dhanera', district: 'Banaskantha', state: 'Gujarat' },
  { name: 'Tharad', district: 'Banaskantha', state: 'Gujarat' },
  { name: 'Chadotar', district: 'Banaskantha', state: 'Gujarat' },
  { name: 'Malan', district: 'Banaskantha', state: 'Gujarat' },
  { name: 'Jagana', district: 'Banaskantha', state: 'Gujarat' },
  { name: 'Vav', district: 'Banaskantha', state: 'Gujarat' },
  { name: 'Danta', district: 'Banaskantha', state: 'Gujarat' },
  { name: 'Amirgadh', district: 'Banaskantha', state: 'Gujarat' },
  { name: 'Shihori (Kankrej)', district: 'Banaskantha', state: 'Gujarat' },

  // Sabarkantha (Himatnagar)
  { name: 'Himatnagar City', district: 'Sabarkantha', state: 'Gujarat' },
  { name: 'Idar', district: 'Sabarkantha', state: 'Gujarat' },
  { name: 'Prantij', district: 'Sabarkantha', state: 'Gujarat' },
  { name: 'Talod', district: 'Sabarkantha', state: 'Gujarat' },
  { name: 'Khedbrahma', district: 'Sabarkantha', state: 'Gujarat' },
  { name: 'Vadali', district: 'Sabarkantha', state: 'Gujarat' },

  // Mehsana
  { name: 'Kadi', district: 'Mehsana', state: 'Gujarat' },
  { name: 'Visnagar', district: 'Mehsana', state: 'Gujarat' },
  { name: 'Unjha', district: 'Mehsana', state: 'Gujarat' },
  { name: 'Vadnagar', district: 'Mehsana', state: 'Gujarat' },
  { name: 'Vijapur', district: 'Mehsana', state: 'Gujarat' },
  { name: 'Becharaji', district: 'Mehsana', state: 'Gujarat' },

  // Kutch
  { name: 'Bhuj City', district: 'Bhuj (Kutch)', state: 'Gujarat' },
  { name: 'Gandhidham', district: 'Bhuj (Kutch)', state: 'Gujarat' },
  { name: 'Anjar', district: 'Bhuj (Kutch)', state: 'Gujarat' },
  { name: 'Mandvi', district: 'Bhuj (Kutch)', state: 'Gujarat' },
  { name: 'Mundra', district: 'Bhuj (Kutch)', state: 'Gujarat' },
  { name: 'Madhapar', district: 'Bhuj (Kutch)', state: 'Gujarat' },
  { name: 'Nakhatrana', district: 'Bhuj (Kutch)', state: 'Gujarat' },
  { name: 'Rapar', district: 'Bhuj (Kutch)', state: 'Gujarat' },
  { name: 'Bhachau', district: 'Bhuj (Kutch)', state: 'Gujarat' },

  // Other Gujarat districts
  { name: 'Morbi City', district: 'Morbi', state: 'Gujarat' },
  { name: 'Wankaner', district: 'Morbi', state: 'Gujarat' },
  { name: 'Halvad', district: 'Morbi', state: 'Gujarat' },
  { name: 'Tankara', district: 'Morbi', state: 'Gujarat' },
  { name: 'Surendranagar City', district: 'Surendranagar', state: 'Gujarat' },
  { name: 'Wadhwan', district: 'Surendranagar', state: 'Gujarat' },
  { name: 'Chotila', district: 'Surendranagar', state: 'Gujarat' },
  { name: 'Dhrangadhra', district: 'Surendranagar', state: 'Gujarat' },
  { name: 'Anand City', district: 'Anand', state: 'Gujarat' },
  { name: 'Vallabh Vidyanagar', district: 'Anand', state: 'Gujarat' },
  { name: 'Karamsad', district: 'Anand', state: 'Gujarat' },
  { name: 'Borsad', district: 'Anand', state: 'Gujarat' },
  { name: 'Petlad', district: 'Anand', state: 'Gujarat' },
  { name: 'Khambhat', district: 'Anand', state: 'Gujarat' },
  { name: 'Nadiad City', district: 'Nadiad (Kheda)', state: 'Gujarat' },
  { name: 'Kapadvanj', district: 'Nadiad (Kheda)', state: 'Gujarat' },
  { name: 'Mehmedabad', district: 'Nadiad (Kheda)', state: 'Gujarat' },
  { name: 'Dakor', district: 'Nadiad (Kheda)', state: 'Gujarat' },
  { name: 'Bharuch City', district: 'Bharuch', state: 'Gujarat' },
  { name: 'Ankleshwar', district: 'Bharuch', state: 'Gujarat' },
  { name: 'Jambusar', district: 'Bharuch', state: 'Gujarat' },
  { name: 'Navsari City', district: 'Navsari', state: 'Gujarat' },
  { name: 'Bilimora', district: 'Navsari', state: 'Gujarat' },
  { name: 'Chikhli', district: 'Navsari', state: 'Gujarat' },
  { name: 'Valsad City', district: 'Valsad', state: 'Gujarat' },
  { name: 'Vapi GIDC', district: 'Valsad', state: 'Gujarat' },
  { name: 'Pardi', district: 'Valsad', state: 'Gujarat' },
  { name: 'Dharampur', district: 'Valsad', state: 'Gujarat' },
  { name: 'Umbergaon', district: 'Valsad', state: 'Gujarat' },
  { name: 'Bhavnagar City', district: 'Bhavnagar', state: 'Gujarat' },
  { name: 'Palitana', district: 'Bhavnagar', state: 'Gujarat' },
  { name: 'Mahuva', district: 'Bhavnagar', state: 'Gujarat' },
  { name: 'Talaja', district: 'Bhavnagar', state: 'Gujarat' },
  { name: 'Jamnagar City', district: 'Jamnagar', state: 'Gujarat' },
  { name: 'Dhrol', district: 'Jamnagar', state: 'Gujarat' },
  { name: 'Kalavad', district: 'Jamnagar', state: 'Gujarat' },
  { name: 'Junagadh City', district: 'Junagadh', state: 'Gujarat' },
  { name: 'Keshod', district: 'Junagadh', state: 'Gujarat' },
  { name: 'Mangrol', district: 'Junagadh', state: 'Gujarat' },
  { name: 'Visavadar', district: 'Junagadh', state: 'Gujarat' },
  { name: 'Porbandar City', district: 'Porbandar', state: 'Gujarat' },
  { name: 'Ranavav', district: 'Porbandar', state: 'Gujarat' },
  { name: 'Veraval', district: 'Veraval (Gir Somnath)', state: 'Gujarat' },
  { name: 'Talala', district: 'Veraval (Gir Somnath)', state: 'Gujarat' },
  { name: 'Una', district: 'Veraval (Gir Somnath)', state: 'Gujarat' },
  { name: 'Kodinar', district: 'Veraval (Gir Somnath)', state: 'Gujarat' },
  { name: 'Godhra', district: 'Godhra (Panchmahal)', state: 'Gujarat' },
  { name: 'Halol', district: 'Godhra (Panchmahal)', state: 'Gujarat' },
  { name: 'Kalol (Panchmahal)', district: 'Godhra (Panchmahal)', state: 'Gujarat' },
  { name: 'Patan City', district: 'Patan', state: 'Gujarat' },
  { name: 'Siddhpur', district: 'Patan', state: 'Gujarat' },
  { name: 'Chanasma', district: 'Patan', state: 'Gujarat' },
  { name: 'Radhanpur', district: 'Patan', state: 'Gujarat' },
  { name: 'Dahod City', district: 'Dahod', state: 'Gujarat' },
  { name: 'Jhalod', district: 'Dahod', state: 'Gujarat' },
  { name: 'Limkheda', district: 'Dahod', state: 'Gujarat' },
  { name: 'Botad City', district: 'Botad', state: 'Gujarat' },
  { name: 'Gadhada', district: 'Botad', state: 'Gujarat' },
  { name: 'Barwala', district: 'Botad', state: 'Gujarat' },
  { name: 'Amreli City', district: 'Amreli', state: 'Gujarat' },
  { name: 'Dhari', district: 'Amreli', state: 'Gujarat' },
  { name: 'Bagasara', district: 'Amreli', state: 'Gujarat' },
  { name: 'Savarkundla', district: 'Amreli', state: 'Gujarat' },
  { name: 'Modasa', district: 'Modasa (Aravalli)', state: 'Gujarat' },
  { name: 'Bayad', district: 'Modasa (Aravalli)', state: 'Gujarat' },
  { name: 'Malpur', district: 'Modasa (Aravalli)', state: 'Gujarat' },
  { name: 'Vyara', district: 'Vyara (Tapi)', state: 'Gujarat' },
  { name: 'Songadh', district: 'Vyara (Tapi)', state: 'Gujarat' },
  { name: 'Dwarka', district: 'Dwarka', state: 'Gujarat' },
  { name: 'Khambhalia', district: 'Dwarka', state: 'Gujarat' },
  { name: 'Chhota Udaipur', district: 'Chhota Udaipur', state: 'Gujarat' },
  { name: 'Bodeli', district: 'Chhota Udaipur', state: 'Gujarat' },
  { name: 'Lunawada', district: 'Mahisagar (Lunawada)', state: 'Gujarat' },
  { name: 'Santrampur', district: 'Mahisagar (Lunawada)', state: 'Gujarat' },
  { name: 'Ahwa', district: 'Dang (Ahwa)', state: 'Gujarat' },
  { name: 'Saputara', district: 'Dang (Ahwa)', state: 'Gujarat' },
  { name: 'Rajpipla', district: 'Narmada (Rajpipla)', state: 'Gujarat' },
  { name: 'Dediyapada', district: 'Narmada (Rajpipla)', state: 'Gujarat' },

  // ==========================================
  // UTTAR PRADESH (Comprehensive coverage)
  // ==========================================
  // Lucknow
  { name: 'Hazratganj', district: 'Lucknow', state: 'Uttar Pradesh' },
  { name: 'Gomti Nagar', district: 'Lucknow', state: 'Uttar Pradesh' },
  { name: 'Alambagh', district: 'Lucknow', state: 'Uttar Pradesh' },
  { name: 'Indira Nagar', district: 'Lucknow', state: 'Uttar Pradesh' },
  { name: 'Aliganj', district: 'Lucknow', state: 'Uttar Pradesh' },
  { name: 'Mahanagar', district: 'Lucknow', state: 'Uttar Pradesh' },
  { name: 'Aminabad', district: 'Lucknow', state: 'Uttar Pradesh' },
  { name: 'Jankipuram', district: 'Lucknow', state: 'Uttar Pradesh' },
  { name: 'Ashiyana', district: 'Lucknow', state: 'Uttar Pradesh' },
  { name: 'Bakshi Ka Talab (BKT)', district: 'Lucknow', state: 'Uttar Pradesh' },
  { name: 'Mohanlalganj', district: 'Lucknow', state: 'Uttar Pradesh' },
  { name: 'Malihabad', district: 'Lucknow', state: 'Uttar Pradesh' },
  { name: 'Kakori', district: 'Lucknow', state: 'Uttar Pradesh' },
  { name: 'Chinhat', district: 'Lucknow', state: 'Uttar Pradesh' },
  { name: 'Sarojini Nagar', district: 'Lucknow', state: 'Uttar Pradesh' },

  // Kanpur Nagar & Kanpur Dehat
  { name: 'Kalyanpur', district: 'Kanpur Nagar', state: 'Uttar Pradesh' },
  { name: 'Govind Nagar', district: 'Kanpur Nagar', state: 'Uttar Pradesh' },
  { name: 'Civil Lines Kanpur', district: 'Kanpur Nagar', state: 'Uttar Pradesh' },
  { name: 'Kakadeo', district: 'Kanpur Nagar', state: 'Uttar Pradesh' },
  { name: 'Kidwai Nagar', district: 'Kanpur Nagar', state: 'Uttar Pradesh' },
  { name: 'Swaroop Nagar', district: 'Kanpur Nagar', state: 'Uttar Pradesh' },
  { name: 'Bithoor', district: 'Kanpur Nagar', state: 'Uttar Pradesh' },
  { name: 'Ghatampur', district: 'Kanpur Nagar', state: 'Uttar Pradesh' },
  { name: 'Bilhaur', district: 'Kanpur Nagar', state: 'Uttar Pradesh' },
  { name: 'Akbarpur', district: 'Kanpur Dehat', state: 'Uttar Pradesh' },
  { name: 'Rura', district: 'Kanpur Dehat', state: 'Uttar Pradesh' },
  { name: 'Bhognipur (Pukhrayan)', district: 'Kanpur Dehat', state: 'Uttar Pradesh' },

  // Varanasi
  { name: 'Assi Ghat', district: 'Varanasi', state: 'Uttar Pradesh' },
  { name: 'Godowlia', district: 'Varanasi', state: 'Uttar Pradesh' },
  { name: 'Lanka', district: 'Varanasi', state: 'Uttar Pradesh' },
  { name: 'Sigra', district: 'Varanasi', state: 'Uttar Pradesh' },
  { name: 'Bhelupur', district: 'Varanasi', state: 'Uttar Pradesh' },
  { name: 'Cantonment Varanasi', district: 'Varanasi', state: 'Uttar Pradesh' },
  { name: 'Shivpur', district: 'Varanasi', state: 'Uttar Pradesh' },
  { name: 'Pindra', district: 'Varanasi', state: 'Uttar Pradesh' },
  { name: 'Rohaniya', district: 'Varanasi', state: 'Uttar Pradesh' },
  { name: 'Sarnath', district: 'Varanasi', state: 'Uttar Pradesh' },
  { name: 'Ramnagar', district: 'Varanasi', state: 'Uttar Pradesh' },

  // Prayagraj (Allahabad)
  { name: 'Civil Lines Prayagraj', district: 'Prayagraj (Allahabad)', state: 'Uttar Pradesh' },
  { name: 'Katra', district: 'Prayagraj (Allahabad)', state: 'Uttar Pradesh' },
  { name: 'Naini', district: 'Prayagraj (Allahabad)', state: 'Uttar Pradesh' },
  { name: 'Allahpur', district: 'Prayagraj (Allahabad)', state: 'Uttar Pradesh' },
  { name: 'Daraganj', district: 'Prayagraj (Allahabad)', state: 'Uttar Pradesh' },
  { name: 'Georgetown', district: 'Prayagraj (Allahabad)', state: 'Uttar Pradesh' },
  { name: 'Jhunsi', district: 'Prayagraj (Allahabad)', state: 'Uttar Pradesh' },
  { name: 'Phulpur', district: 'Prayagraj (Allahabad)', state: 'Uttar Pradesh' },
  { name: 'Soraon', district: 'Prayagraj (Allahabad)', state: 'Uttar Pradesh' },
  { name: 'Koraon', district: 'Prayagraj (Allahabad)', state: 'Uttar Pradesh' },
  { name: 'Meja', district: 'Prayagraj (Allahabad)', state: 'Uttar Pradesh' },

  // Agra
  { name: 'Tajganj', district: 'Agra', state: 'Uttar Pradesh' },
  { name: 'Sanjay Place', district: 'Agra', state: 'Uttar Pradesh' },
  { name: 'Kamla Nagar', district: 'Agra', state: 'Uttar Pradesh' },
  { name: 'Dayalbagh', district: 'Agra', state: 'Uttar Pradesh' },
  { name: 'Fatehabad', district: 'Agra', state: 'Uttar Pradesh' },
  { name: 'Kheragarh', district: 'Agra', state: 'Uttar Pradesh' },
  { name: 'Etmadpur', district: 'Agra', state: 'Uttar Pradesh' },
  { name: 'Bah', district: 'Agra', state: 'Uttar Pradesh' },

  // Gautam Buddha Nagar & Ghaziabad
  { name: 'Sector 62 Noida', district: 'Gautam Buddha Nagar (Noida)', state: 'Uttar Pradesh' },
  { name: 'Sector 18 Noida', district: 'Gautam Buddha Nagar (Noida)', state: 'Uttar Pradesh' },
  { name: 'Pari Chowk', district: 'Gautam Buddha Nagar (Noida)', state: 'Uttar Pradesh' },
  { name: 'Knowledge Park', district: 'Gautam Buddha Nagar (Noida)', state: 'Uttar Pradesh' },
  { name: 'Dadri', district: 'Gautam Buddha Nagar (Noida)', state: 'Uttar Pradesh' },
  { name: 'Jewar', district: 'Gautam Buddha Nagar (Noida)', state: 'Uttar Pradesh' },
  { name: 'Dankaur', district: 'Gautam Buddha Nagar (Noida)', state: 'Uttar Pradesh' },
  { name: 'Indirapuram', district: 'Ghaziabad', state: 'Uttar Pradesh' },
  { name: 'Vaishali', district: 'Ghaziabad', state: 'Uttar Pradesh' },
  { name: 'Vasundhara', district: 'Ghaziabad', state: 'Uttar Pradesh' },
  { name: 'Raj Nagar Extension', district: 'Ghaziabad', state: 'Uttar Pradesh' },
  { name: 'Crossings Republik', district: 'Ghaziabad', state: 'Uttar Pradesh' },
  { name: 'Loni', district: 'Ghaziabad', state: 'Uttar Pradesh' },
  { name: 'Muradnagar', district: 'Ghaziabad', state: 'Uttar Pradesh' },
  { name: 'Modinagar', district: 'Ghaziabad', state: 'Uttar Pradesh' },

  // Meerut, Aligarh, Mathura, Ayodhya, Gorakhpur, Bareilly, Jhansi
  { name: 'Shastri Nagar', district: 'Meerut', state: 'Uttar Pradesh' },
  { name: 'Civil Lines Meerut', district: 'Meerut', state: 'Uttar Pradesh' },
  { name: 'Pallavpuram', district: 'Meerut', state: 'Uttar Pradesh' },
  { name: 'Sardhana', district: 'Meerut', state: 'Uttar Pradesh' },
  { name: 'Mawana', district: 'Meerut', state: 'Uttar Pradesh' },
  { name: 'Centre Point', district: 'Aligarh', state: 'Uttar Pradesh' },
  { name: 'Civil Lines Aligarh', district: 'Aligarh', state: 'Uttar Pradesh' },
  { name: 'Atrauli', district: 'Aligarh', state: 'Uttar Pradesh' },
  { name: 'Iglas', district: 'Aligarh', state: 'Uttar Pradesh' },
  { name: 'Khair', district: 'Aligarh', state: 'Uttar Pradesh' },
  { name: 'Krishna Nagar', district: 'Mathura', state: 'Uttar Pradesh' },
  { name: 'Vrindavan', district: 'Mathura', state: 'Uttar Pradesh' },
  { name: 'Goverdhan', district: 'Mathura', state: 'Uttar Pradesh' },
  { name: 'Barsana', district: 'Mathura', state: 'Uttar Pradesh' },
  { name: 'Chhata', district: 'Mathura', state: 'Uttar Pradesh' },
  { name: 'Ram Janmabhoomi Area', district: 'Ayodhya', state: 'Uttar Pradesh' },
  { name: 'Civil Lines Ayodhya', district: 'Ayodhya', state: 'Uttar Pradesh' },
  { name: 'Faizabad Chowk', district: 'Ayodhya', state: 'Uttar Pradesh' },
  { name: 'Rudauli', district: 'Ayodhya', state: 'Uttar Pradesh' },
  { name: 'Bikapur', district: 'Ayodhya', state: 'Uttar Pradesh' },
  { name: 'Golghar', district: 'Gorakhpur', state: 'Uttar Pradesh' },
  { name: 'Gorakhnath', district: 'Gorakhpur', state: 'Uttar Pradesh' },
  { name: 'Medical College Road', district: 'Gorakhpur', state: 'Uttar Pradesh' },
  { name: 'Sahjanwa', district: 'Gorakhpur', state: 'Uttar Pradesh' },
  { name: 'Chauri Chaura', district: 'Gorakhpur', state: 'Uttar Pradesh' },
  { name: 'Civil Lines Bareilly', district: 'Bareilly', state: 'Uttar Pradesh' },
  { name: 'Rajendra Nagar', district: 'Bareilly', state: 'Uttar Pradesh' },
  { name: 'Aonla', district: 'Bareilly', state: 'Uttar Pradesh' },
  { name: 'Baheri', district: 'Bareilly', state: 'Uttar Pradesh' },
  { name: 'Sadar Bazar Jhansi', district: 'Jhansi', state: 'Uttar Pradesh' },
  { name: 'Civil Lines Jhansi', district: 'Jhansi', state: 'Uttar Pradesh' },
  { name: 'Mauranipur', district: 'Jhansi', state: 'Uttar Pradesh' },
  { name: 'Babina', district: 'Jhansi', state: 'Uttar Pradesh' },

  // Other key UP districts
  { name: 'Civil Lines Moradabad', district: 'Moradabad', state: 'Uttar Pradesh' },
  { name: 'Kanth', district: 'Moradabad', state: 'Uttar Pradesh' },
  { name: 'Bilari', district: 'Moradabad', state: 'Uttar Pradesh' },
  { name: 'Civil Lines Saharanpur', district: 'Saharanpur', state: 'Uttar Pradesh' },
  { name: 'Deoband', district: 'Saharanpur', state: 'Uttar Pradesh' },
  { name: 'Behat', district: 'Saharanpur', state: 'Uttar Pradesh' },
  { name: 'Civil Lines Muzaffarnagar', district: 'Muzaffarnagar', state: 'Uttar Pradesh' },
  { name: 'Khatauli', district: 'Muzaffarnagar', state: 'Uttar Pradesh' },
  { name: 'Budhana', district: 'Muzaffarnagar', state: 'Uttar Pradesh' },
  { name: 'Firozabad City', district: 'Firozabad', state: 'Uttar Pradesh' },
  { name: 'Shikohabad', district: 'Firozabad', state: 'Uttar Pradesh' },
  { name: 'Tundla', district: 'Firozabad', state: 'Uttar Pradesh' },
  { name: 'Amethi Town', district: 'Amethi', state: 'Uttar Pradesh' },
  { name: 'Gauriganj', district: 'Amethi', state: 'Uttar Pradesh' },
  { name: 'Tiloi', district: 'Amethi', state: 'Uttar Pradesh' },
  { name: 'Musafirkhana', district: 'Amethi', state: 'Uttar Pradesh' },
  { name: 'Azamgarh City', district: 'Azamgarh', state: 'Uttar Pradesh' },
  { name: 'Sagri', district: 'Azamgarh', state: 'Uttar Pradesh' },
  { name: 'Phoolpur (Azamgarh)', district: 'Azamgarh', state: 'Uttar Pradesh' },
  { name: 'Ballia City', district: 'Ballia', state: 'Uttar Pradesh' },
  { name: 'Rasra', district: 'Ballia', state: 'Uttar Pradesh' },
  { name: 'Bansdih', district: 'Ballia', state: 'Uttar Pradesh' },
  { name: 'Basti City', district: 'Basti', state: 'Uttar Pradesh' },
  { name: 'Harraiya', district: 'Basti', state: 'Uttar Pradesh' },
  { name: 'Deoria City', district: 'Deoria', state: 'Uttar Pradesh' },
  { name: 'Salempur', district: 'Deoria', state: 'Uttar Pradesh' },
  { name: 'Bhatpar Rani', district: 'Deoria', state: 'Uttar Pradesh' },
  { name: 'Jaunpur City', district: 'Jaunpur', state: 'Uttar Pradesh' },
  { name: 'Shahganj', district: 'Jaunpur', state: 'Uttar Pradesh' },
  { name: 'Machhlishahr', district: 'Jaunpur', state: 'Uttar Pradesh' },
  { name: 'Raebareli City', district: 'Raebareli', state: 'Uttar Pradesh' },
  { name: 'Lalganj', district: 'Raebareli', state: 'Uttar Pradesh' },
  { name: 'Salon', district: 'Raebareli', state: 'Uttar Pradesh' },
  { name: 'Sitapur City', district: 'Sitapur', state: 'Uttar Pradesh' },
  { name: 'Biswan', district: 'Sitapur', state: 'Uttar Pradesh' },
  { name: 'Mahmoodabad', district: 'Sitapur', state: 'Uttar Pradesh' },
  { name: 'Sultanpur City', district: 'Sultanpur', state: 'Uttar Pradesh' },
  { name: 'Kadipur', district: 'Sultanpur', state: 'Uttar Pradesh' },
  { name: 'Lambhua', district: 'Sultanpur', state: 'Uttar Pradesh' },
  { name: 'Unnao City', district: 'Unnao', state: 'Uttar Pradesh' },
  { name: 'Shuklaganj', district: 'Unnao', state: 'Uttar Pradesh' },
  { name: 'Safipur', district: 'Unnao', state: 'Uttar Pradesh' },
  { name: 'Purwa', district: 'Unnao', state: 'Uttar Pradesh' },
  { name: 'Barabanki City', district: 'Barabanki', state: 'Uttar Pradesh' },
  { name: 'Nawabganj', district: 'Barabanki', state: 'Uttar Pradesh' },
  { name: 'Fatehpur (Barabanki)', district: 'Barabanki', state: 'Uttar Pradesh' },
  { name: 'Rampur City', district: 'Rampur', state: 'Uttar Pradesh' },
  { name: 'Bilaspur (Rampur)', district: 'Rampur', state: 'Uttar Pradesh' },
  { name: 'Mirzapur City', district: 'Mirzapur', state: 'Uttar Pradesh' },
  { name: 'Chunar', district: 'Mirzapur', state: 'Uttar Pradesh' },
  { name: 'Vindhyachal', district: 'Mirzapur', state: 'Uttar Pradesh' },
  { name: 'Ghazipur City', district: 'Ghazipur', state: 'Uttar Pradesh' },
  { name: 'Zamania', district: 'Ghazipur', state: 'Uttar Pradesh' },
  { name: 'Mohammadabad', district: 'Ghazipur', state: 'Uttar Pradesh' },
  { name: 'Gonda City', district: 'Gonda', state: 'Uttar Pradesh' },
  { name: 'Colonelganj', district: 'Gonda', state: 'Uttar Pradesh' },
  { name: 'Tarabganj', district: 'Gonda', state: 'Uttar Pradesh' },
  { name: 'Mankapur', district: 'Gonda', state: 'Uttar Pradesh' },
  { name: 'Bahraich City', district: 'Bahraich', state: 'Uttar Pradesh' },
  { name: 'Nanpara', district: 'Bahraich', state: 'Uttar Pradesh' },
  { name: 'Kaiserganj', district: 'Bahraich', state: 'Uttar Pradesh' },
  { name: 'Banda City', district: 'Banda', state: 'Uttar Pradesh' },
  { name: 'Atarra', district: 'Banda', state: 'Uttar Pradesh' },
  { name: 'Baberu', district: 'Banda', state: 'Uttar Pradesh' },
  { name: 'Hardoi City', district: 'Hardoi', state: 'Uttar Pradesh' },
  { name: 'Sandila', district: 'Hardoi', state: 'Uttar Pradesh' },
  { name: 'Shahabad (Hardoi)', district: 'Hardoi', state: 'Uttar Pradesh' },
  { name: 'Bilgram', district: 'Hardoi', state: 'Uttar Pradesh' },
  { name: 'Lakhimpur Town', district: 'Kheri (Lakhimpur)', state: 'Uttar Pradesh' },
  { name: 'Gola Gokaran Nath', district: 'Kheri (Lakhimpur)', state: 'Uttar Pradesh' },
  { name: 'Mohammadi', district: 'Kheri (Lakhimpur)', state: 'Uttar Pradesh' },
  { name: 'Farrukhabad City', district: 'Farrukhabad', state: 'Uttar Pradesh' },
  { name: 'Fatehgarh', district: 'Farrukhabad', state: 'Uttar Pradesh' },
  { name: 'Kaimganj', district: 'Farrukhabad', state: 'Uttar Pradesh' },
  { name: 'Mainpuri City', district: 'Mainpuri', state: 'Uttar Pradesh' },
  { name: 'Bhongaon', district: 'Mainpuri', state: 'Uttar Pradesh' },
  { name: 'Karhal', district: 'Mainpuri', state: 'Uttar Pradesh' },
  { name: 'Etawah City', district: 'Etawah', state: 'Uttar Pradesh' },
  { name: 'Saifai', district: 'Etawah', state: 'Uttar Pradesh' },
  { name: 'Jaswantnagar', district: 'Etawah', state: 'Uttar Pradesh' },
  { name: 'Bharthana', district: 'Etawah', state: 'Uttar Pradesh' },
  { name: 'Etah City', district: 'Etah', state: 'Uttar Pradesh' },
  { name: 'Jalesar', district: 'Etah', state: 'Uttar Pradesh' },
  { name: 'Aliganj (Etah)', district: 'Etah', state: 'Uttar Pradesh' },
  { name: 'Hathras City', district: 'Hathras', state: 'Uttar Pradesh' },
  { name: 'Sadabad', district: 'Hathras', state: 'Uttar Pradesh' },
  { name: 'Sasni', district: 'Hathras', state: 'Uttar Pradesh' },
  { name: 'Bijnor City', district: 'Bijnor', state: 'Uttar Pradesh' },
  { name: 'Najibabad', district: 'Bijnor', state: 'Uttar Pradesh' },
  { name: 'Chandpur', district: 'Bijnor', state: 'Uttar Pradesh' },
  { name: 'Nagina', district: 'Bijnor', state: 'Uttar Pradesh' },
  { name: 'Badaun City', district: 'Badaun', state: 'Uttar Pradesh' },
  { name: 'Ujhani', district: 'Badaun', state: 'Uttar Pradesh' },
  { name: 'Bilsi', district: 'Badaun', state: 'Uttar Pradesh' },
  { name: 'Bisauli', district: 'Badaun', state: 'Uttar Pradesh' },
  { name: 'Bulandshahr City', district: 'Bulandshahr', state: 'Uttar Pradesh' },
  { name: 'Khurja', district: 'Bulandshahr', state: 'Uttar Pradesh' },
  { name: 'Sikandrabad', district: 'Bulandshahr', state: 'Uttar Pradesh' },
  { name: 'Anupshahr', district: 'Bulandshahr', state: 'Uttar Pradesh' },
  { name: 'Pilibhit City', district: 'Pilibhit', state: 'Uttar Pradesh' },
  { name: 'Bisalpur', district: 'Pilibhit', state: 'Uttar Pradesh' },
  { name: 'Pooranpur', district: 'Pilibhit', state: 'Uttar Pradesh' },
  { name: 'Shahjahanpur City', district: 'Shahjahanpur', state: 'Uttar Pradesh' },
  { name: 'Tilhar', district: 'Shahjahanpur', state: 'Uttar Pradesh' },
  { name: 'Puwayan', district: 'Shahjahanpur', state: 'Uttar Pradesh' },
  { name: 'Jalaun (Orai)', district: 'Jalaun (Orai)', state: 'Uttar Pradesh' },
  { name: 'Konch', district: 'Jalaun (Orai)', state: 'Uttar Pradesh' },
  { name: 'Kalpi', district: 'Jalaun (Orai)', state: 'Uttar Pradesh' },

  // ==========================================
  // MAHARASHTRA
  // ==========================================
  { name: 'Andheri West', district: 'Mumbai', state: 'Maharashtra' },
  { name: 'Andheri East', district: 'Mumbai', state: 'Maharashtra' },
  { name: 'Bandra West', district: 'Mumbai', state: 'Maharashtra' },
  { name: 'Borivali West', district: 'Mumbai', state: 'Maharashtra' },
  { name: 'Dadar', district: 'Mumbai', state: 'Maharashtra' },
  { name: 'Malad West', district: 'Mumbai', state: 'Maharashtra' },
  { name: 'Ghatkopar East', district: 'Mumbai', state: 'Maharashtra' },
  { name: 'Kandivali', district: 'Mumbai', state: 'Maharashtra' },
  { name: 'Kurla', district: 'Mumbai', state: 'Maharashtra' },
  { name: 'Chembur', district: 'Mumbai', state: 'Maharashtra' },
  { name: 'Powai', district: 'Mumbai', state: 'Maharashtra' },
  { name: 'Mulund', district: 'Mumbai', state: 'Maharashtra' },
  { name: 'Thane West', district: 'Thane', state: 'Maharashtra' },
  { name: 'Ghubunder Road', district: 'Thane', state: 'Maharashtra' },
  { name: 'Majiwada', district: 'Thane', state: 'Maharashtra' },
  { name: 'Kalyan West', district: 'Thane', state: 'Maharashtra' },
  { name: 'Dombivli East', district: 'Thane', state: 'Maharashtra' },
  { name: 'Mira Road', district: 'Thane', state: 'Maharashtra' },
  { name: 'Bhayandar', district: 'Thane', state: 'Maharashtra' },
  { name: 'Ulhasnagar', district: 'Thane', state: 'Maharashtra' },
  { name: 'Bhiwandi', district: 'Thane', state: 'Maharashtra' },
  { name: 'Vashi', district: 'Navi Mumbai', state: 'Maharashtra' },
  { name: 'Nerul', district: 'Navi Mumbai', state: 'Maharashtra' },
  { name: 'Kharghar', district: 'Navi Mumbai', state: 'Maharashtra' },
  { name: 'Belapur', district: 'Navi Mumbai', state: 'Maharashtra' },
  { name: 'Panvel', district: 'Navi Mumbai', state: 'Maharashtra' },
  { name: 'Airoli', district: 'Navi Mumbai', state: 'Maharashtra' },
  { name: 'Shivaji Nagar', district: 'Pune', state: 'Maharashtra' },
  { name: 'Kothrud', district: 'Pune', state: 'Maharashtra' },
  { name: 'Hadapsar', district: 'Pune', state: 'Maharashtra' },
  { name: 'Hinjewadi', district: 'Pune', state: 'Maharashtra' },
  { name: 'Baner', district: 'Pune', state: 'Maharashtra' },
  { name: 'Viman Nagar', district: 'Pune', state: 'Maharashtra' },
  { name: 'Wakad', district: 'Pune', state: 'Maharashtra' },
  { name: 'Aundh', district: 'Pune', state: 'Maharashtra' },
  { name: 'Pimpri', district: 'Pune', state: 'Maharashtra' },
  { name: 'Chinchwad', district: 'Pune', state: 'Maharashtra' },
  { name: 'Bhosari', district: 'Pune', state: 'Maharashtra' },
  { name: 'Baramati', district: 'Pune', state: 'Maharashtra' },
  { name: 'Dharampeth', district: 'Nagpur', state: 'Maharashtra' },
  { name: 'Sitabuldi', district: 'Nagpur', state: 'Maharashtra' },
  { name: 'Manish Nagar', district: 'Nagpur', state: 'Maharashtra' },
  { name: 'Ramdaspeth', district: 'Nagpur', state: 'Maharashtra' },
  { name: 'Kamptee', district: 'Nagpur', state: 'Maharashtra' },
  { name: 'College Road', district: 'Nashik', state: 'Maharashtra' },
  { name: 'Gangapur Road', district: 'Nashik', state: 'Maharashtra' },
  { name: 'Indira Nagar Nashik', district: 'Nashik', state: 'Maharashtra' },
  { name: 'Panchavati', district: 'Nashik', state: 'Maharashtra' },
  { name: 'Deolali', district: 'Nashik', state: 'Maharashtra' },
  { name: 'Cidco', district: 'Chhatrapati Sambhajinagar (Aurangabad)', state: 'Maharashtra' },
  { name: 'Garkheda', district: 'Chhatrapati Sambhajinagar (Aurangabad)', state: 'Maharashtra' },
  { name: 'Waluj', district: 'Chhatrapati Sambhajinagar (Aurangabad)', state: 'Maharashtra' },
  { name: 'Chikli', district: 'Chhatrapati Sambhajinagar (Aurangabad)', state: 'Maharashtra' },
  { name: 'Rajarampuri', district: 'Kolhapur', state: 'Maharashtra' },
  { name: 'Tarabai Park', district: 'Kolhapur', state: 'Maharashtra' },
  { name: 'Ichalkaranji', district: 'Kolhapur', state: 'Maharashtra' },
  { name: 'Jule Solapur', district: 'Solapur', state: 'Maharashtra' },
  { name: 'Hotgi Road', district: 'Solapur', state: 'Maharashtra' },
  { name: 'Barshi', district: 'Solapur', state: 'Maharashtra' },

  // ==========================================
  // RAJASTHAN
  // ==========================================
  { name: 'Mansarovar', district: 'Jaipur', state: 'Rajasthan' },
  { name: 'Malviya Nagar', district: 'Jaipur', state: 'Rajasthan' },
  { name: 'Vaishali Nagar', district: 'Jaipur', state: 'Rajasthan' },
  { name: 'Sanganer', district: 'Jaipur', state: 'Rajasthan' },
  { name: 'Raja Park', district: 'Jaipur', state: 'Rajasthan' },
  { name: 'C-Scheme', district: 'Jaipur', state: 'Rajasthan' },
  { name: 'Jagatpura', district: 'Jaipur', state: 'Rajasthan' },
  { name: 'Ajmer Road', district: 'Jaipur', state: 'Rajasthan' },
  { name: 'Chomu', district: 'Jaipur', state: 'Rajasthan' },
  { name: 'Sardarpura', district: 'Jodhpur', state: 'Rajasthan' },
  { name: 'Shastri Nagar Jodhpur', district: 'Jodhpur', state: 'Rajasthan' },
  { name: 'Ratanada', district: 'Jodhpur', state: 'Rajasthan' },
  { name: 'Mandore', district: 'Jodhpur', state: 'Rajasthan' },
  { name: 'Sukhadia Circle', district: 'Udaipur', state: 'Rajasthan' },
  { name: 'Fatehpura', district: 'Udaipur', state: 'Rajasthan' },
  { name: 'Hiran Magri', district: 'Udaipur', state: 'Rajasthan' },
  { name: 'Panchwati Udaipur', district: 'Udaipur', state: 'Rajasthan' },
  { name: 'Talwandi', district: 'Kota', state: 'Rajasthan' },
  { name: 'Vigyan Nagar', district: 'Kota', state: 'Rajasthan' },
  { name: 'Mahaveer Nagar', district: 'Kota', state: 'Rajasthan' },
  { name: 'Civil Lines Ajmer', district: 'Ajmer', state: 'Rajasthan' },
  { name: 'Pushkar', district: 'Ajmer', state: 'Rajasthan' },
  { name: 'Kishangarh', district: 'Ajmer', state: 'Rajasthan' },
  { name: 'Karni Nagar', district: 'Bikaner', state: 'Rajasthan' },
  { name: 'Sadul Colony', district: 'Bikaner', state: 'Rajasthan' },
  { name: 'Nokha', district: 'Bikaner', state: 'Rajasthan' },
  { name: 'Bhopalganj', district: 'Bhilwara', state: 'Rajasthan' },
  { name: 'Subhash Nagar Bhilwara', district: 'Bhilwara', state: 'Rajasthan' },
  { name: 'Moti Doongri Alwar', district: 'Alwar', state: 'Rajasthan' },
  { name: 'Bhiwadi', district: 'Alwar', state: 'Rajasthan' },
  { name: 'Neemrana', district: 'Alwar', state: 'Rajasthan' },
  { name: 'Piprali Road', district: 'Sikar', state: 'Rajasthan' },
  { name: 'Fatehpur Shekhawati', district: 'Sikar', state: 'Rajasthan' },
  { name: 'Surajgarh', district: 'Jhunjhunu', state: 'Rajasthan' },
  { name: 'Pilani', district: 'Jhunjhunu', state: 'Rajasthan' },
  { name: 'Balotra', district: 'Barmer', state: 'Rajasthan' },
  { name: 'Siwana', district: 'Barmer', state: 'Rajasthan' },
  { name: 'Abu Road', district: 'Sirohi', state: 'Rajasthan' },
  { name: 'Mount Abu', district: 'Sirohi', state: 'Rajasthan' },

  // ==========================================
  // MADHYA PRADESH
  // ==========================================
  { name: 'Vijay Nagar', district: 'Indore', state: 'Madhya Pradesh' },
  { name: 'Palasia', district: 'Indore', state: 'Madhya Pradesh' },
  { name: 'Rajwada', district: 'Indore', state: 'Madhya Pradesh' },
  { name: 'Bhawarkua', district: 'Indore', state: 'Madhya Pradesh' },
  { name: 'Rau', district: 'Indore', state: 'Madhya Pradesh' },
  { name: 'Mhow', district: 'Indore', state: 'Madhya Pradesh' },
  { name: 'MP Nagar', district: 'Bhopal', state: 'Madhya Pradesh' },
  { name: 'Arera Colony', district: 'Bhopal', state: 'Madhya Pradesh' },
  { name: 'Kolar Road', district: 'Bhopal', state: 'Madhya Pradesh' },
  { name: 'Hoshangabad Road Bhopal', district: 'Bhopal', state: 'Madhya Pradesh' },
  { name: 'Bairagarh', district: 'Bhopal', state: 'Madhya Pradesh' },
  { name: 'City Center Gwalior', district: 'Gwalior', state: 'Madhya Pradesh' },
  { name: 'Morar', district: 'Gwalior', state: 'Madhya Pradesh' },
  { name: 'Lashkar', district: 'Gwalior', state: 'Madhya Pradesh' },
  { name: 'Civil Lines Jabalpur', district: 'Jabalpur', state: 'Madhya Pradesh' },
  { name: 'Wright Town', district: 'Jabalpur', state: 'Madhya Pradesh' },
  { name: 'Vijay Nagar Jabalpur', district: 'Jabalpur', state: 'Madhya Pradesh' },
  { name: 'Freeganj', district: 'Ujjain', state: 'Madhya Pradesh' },
  { name: 'Mahakal Area', district: 'Ujjain', state: 'Madhya Pradesh' },
  { name: 'Nagda', district: 'Ujjain', state: 'Madhya Pradesh' },
  { name: 'Civil Lines Sagar', district: 'Sagar', state: 'Madhya Pradesh' },
  { name: 'Makronia', district: 'Sagar', state: 'Madhya Pradesh' },
  { name: 'Civil Lines Rewa', district: 'Rewa', state: 'Madhya Pradesh' },
  { name: 'Civil Lines Satna', district: 'Satna', state: 'Madhya Pradesh' },
  { name: 'Maihar', district: 'Satna', state: 'Madhya Pradesh' },

  // ==========================================
  // DELHI (NCT)
  // ==========================================
  { name: 'Connaught Place', district: 'New Delhi', state: 'Delhi (NCT)' },
  { name: 'Chanakyapuri', district: 'New Delhi', state: 'Delhi (NCT)' },
  { name: 'Karol Bagh', district: 'Central Delhi', state: 'Delhi (NCT)' },
  { name: 'Pahar Ganj', district: 'Central Delhi', state: 'Delhi (NCT)' },
  { name: 'Chandni Chowk', district: 'North Delhi', state: 'Delhi (NCT)' },
  { name: 'Civil Lines Delhi', district: 'North Delhi', state: 'Delhi (NCT)' },
  { name: 'Lajpat Nagar', district: 'South Delhi', state: 'Delhi (NCT)' },
  { name: 'Saket', district: 'South Delhi', state: 'Delhi (NCT)' },
  { name: 'Hauz Khas', district: 'South Delhi', state: 'Delhi (NCT)' },
  { name: 'Greater Kailash', district: 'South Delhi', state: 'Delhi (NCT)' },
  { name: 'Rohini Sector 1-25', district: 'North West Delhi', state: 'Delhi (NCT)' },
  { name: 'Pitampura', district: 'North West Delhi', state: 'Delhi (NCT)' },
  { name: 'Dwarka Sector 1-24', district: 'South West Delhi', state: 'Delhi (NCT)' },
  { name: 'Janakpuri', district: 'West Delhi', state: 'Delhi (NCT)' },
  { name: 'Rajouri Garden', district: 'West Delhi', state: 'Delhi (NCT)' },
  { name: 'Mayur Vihar', district: 'East Delhi', state: 'Delhi (NCT)' },
  { name: 'Preet Vihar', district: 'East Delhi', state: 'Delhi (NCT)' },
  { name: 'Shahdara Town', district: 'Shahdara', state: 'Delhi (NCT)' },
  { name: 'Dilshad Garden', district: 'Shahdara', state: 'Delhi (NCT)' },

  // ==========================================
  // BIHAR
  // ==========================================
  { name: 'Kankarbagh', district: 'Patna', state: 'Bihar' },
  { name: 'Boring Road', district: 'Patna', state: 'Bihar' },
  { name: 'Bailey Road', district: 'Patna', state: 'Bihar' },
  { name: 'Danapur Cantt', district: 'Patna', state: 'Bihar' },
  { name: 'Patliputra Colony', district: 'Patna', state: 'Bihar' },
  { name: 'Rajendra Nagar Patna', district: 'Patna', state: 'Bihar' },
  { name: 'Phulwari Sharif', district: 'Patna', state: 'Bihar' },
  { name: 'Civil Lines Gaya', district: 'Gaya', state: 'Bihar' },
  { name: 'Bodh Gaya', district: 'Gaya', state: 'Bihar' },
  { name: 'Tekari', district: 'Gaya', state: 'Bihar' },
  { name: 'Zero Mile', district: 'Bhagalpur', state: 'Bihar' },
  { name: 'Kahalgaon', district: 'Bhagalpur', state: 'Bihar' },
  { name: 'Mithanpura', district: 'Muzaffarpur', state: 'Bihar' },
  { name: 'Brahmpura', district: 'Muzaffarpur', state: 'Bihar' },
  { name: 'Kanti', district: 'Muzaffarpur', state: 'Bihar' },
  { name: 'Line Bazar', district: 'Purnia', state: 'Bihar' },
  { name: 'Banmankhi', district: 'Purnia', state: 'Bihar' },
  { name: 'Laheriasarai', district: 'Darbhanga', state: 'Bihar' },
  { name: 'Benipur', district: 'Darbhanga', state: 'Bihar' },
  { name: 'Harnaut', district: 'Bihar Sharif (Nalanda)', state: 'Bihar' },
  { name: 'Rajgir', district: 'Bihar Sharif (Nalanda)', state: 'Bihar' },
  { name: 'Hilsa', district: 'Bihar Sharif (Nalanda)', state: 'Bihar' },
  { name: 'Arrah Town', district: 'Arrah (Bhojpur)', state: 'Bihar' },
  { name: 'Jagdishpur', district: 'Arrah (Bhojpur)', state: 'Bihar' },
  { name: 'Barauni', district: 'Begusarai', state: 'Bihar' },
  { name: 'Teghra', district: 'Begusarai', state: 'Bihar' },
  { name: 'Manihari', district: 'Katihar', state: 'Bihar' },
  { name: 'Barari', district: 'Katihar', state: 'Bihar' },
  { name: 'Jamalpur', district: 'Munger', state: 'Bihar' },
  { name: 'Sonpur', district: 'Chhapra (Saran)', state: 'Bihar' },
  { name: 'Marhaura', district: 'Chhapra (Saran)', state: 'Bihar' },
  { name: 'Hajipur Town', district: 'Hajipur (Vaishali)', state: 'Bihar' },
  { name: 'Mahua', district: 'Hajipur (Vaishali)', state: 'Bihar' },
  { name: 'Sasaram City', district: 'Sasaram (Rohtas)', state: 'Bihar' },
  { name: 'Dehri On Sone', district: 'Sasaram (Rohtas)', state: 'Bihar' },

  // ==========================================
  // HARYANA
  // ==========================================
  { name: 'DLF Phase 1-5', district: 'Gurugram', state: 'Haryana' },
  { name: 'Sohna Road', district: 'Gurugram', state: 'Haryana' },
  { name: 'Cyber City', district: 'Gurugram', state: 'Haryana' },
  { name: 'Golf Course Road', district: 'Gurugram', state: 'Haryana' },
  { name: 'Palam Vihar', district: 'Gurugram', state: 'Haryana' },
  { name: 'Manesar', district: 'Gurugram', state: 'Haryana' },
  { name: 'Sector 14-16 Faridabad', district: 'Faridabad', state: 'Haryana' },
  { name: 'Ballabgarh', district: 'Faridabad', state: 'Haryana' },
  { name: 'Greater Faridabad (Neharpar)', district: 'Faridabad', state: 'Haryana' },
  { name: 'Model Town Panipat', district: 'Panipat', state: 'Haryana' },
  { name: 'Samalkha', district: 'Panipat', state: 'Haryana' },
  { name: 'Ambala Cantt', district: 'Ambala', state: 'Haryana' },
  { name: 'Ambala City', district: 'Ambala', state: 'Haryana' },
  { name: 'Model Town Rohtak', district: 'Rohtak', state: 'Haryana' },
  { name: 'Meham', district: 'Rohtak', state: 'Haryana' },
  { name: 'Model Town Hisar', district: 'Hisar', state: 'Haryana' },
  { name: 'Hansi', district: 'Hisar', state: 'Haryana' },
  { name: 'Model Town Karnal', district: 'Karnal', state: 'Haryana' },
  { name: 'Gharaunda', district: 'Karnal', state: 'Haryana' },
  { name: 'Kundli', district: 'Sonipat', state: 'Haryana' },
  { name: 'Gohana', district: 'Sonipat', state: 'Haryana' },
  { name: 'Sector 1-20 Panchkula', district: 'Panchkula', state: 'Haryana' },
  { name: 'Kalka', district: 'Panchkula', state: 'Haryana' },
  { name: 'Pinjore', district: 'Panchkula', state: 'Haryana' },

  // ==========================================
  // PUNJAB
  // ==========================================
  { name: 'Model Town Ludhiana', district: 'Ludhiana', state: 'Punjab' },
  { name: 'Sarabha Nagar', district: 'Ludhiana', state: 'Punjab' },
  { name: 'BRS Nagar', district: 'Ludhiana', state: 'Punjab' },
  { name: 'Civil Lines Ludhiana', district: 'Ludhiana', state: 'Punjab' },
  { name: 'Jagraon', district: 'Ludhiana', state: 'Punjab' },
  { name: 'Khanna', district: 'Ludhiana', state: 'Punjab' },
  { name: 'Ranjit Avenue', district: 'Amritsar', state: 'Punjab' },
  { name: 'Lawrence Road Amritsar', district: 'Amritsar', state: 'Punjab' },
  { name: 'Majitha', district: 'Amritsar', state: 'Punjab' },
  { name: 'Model Town Jalandhar', district: 'Jalandhar', state: 'Punjab' },
  { name: 'Urban Estate Jalandhar', district: 'Jalandhar', state: 'Punjab' },
  { name: 'Nakodar', district: 'Jalandhar', state: 'Punjab' },
  { name: 'Phagwara', district: 'Kapurthala', state: 'Punjab' },
  { name: 'Civil Lines Patiala', district: 'Patiala', state: 'Punjab' },
  { name: 'Nabha', district: 'Patiala', state: 'Punjab' },
  { name: 'Rajpura', district: 'Patiala', state: 'Punjab' },
  { name: 'Civil Lines Bathinda', district: 'Bathinda', state: 'Punjab' },
  { name: 'Talwandi Sabo', district: 'Bathinda', state: 'Punjab' },
  { name: 'Phase 1-11 Mohali', district: 'Mohali (SAS Nagar)', state: 'Punjab' },
  { name: 'Kharar', district: 'Mohali (SAS Nagar)', state: 'Punjab' },
  { name: 'Zirakpur', district: 'Mohali (SAS Nagar)', state: 'Punjab' },
  { name: 'Dera Bassi', district: 'Mohali (SAS Nagar)', state: 'Punjab' },

  // ==========================================
  // KARNATAKA
  // ==========================================
  { name: 'Indiranagar', district: 'Bengaluru Urban', state: 'Karnataka' },
  { name: 'Koramangala', district: 'Bengaluru Urban', state: 'Karnataka' },
  { name: 'Whitefield', district: 'Bengaluru Urban', state: 'Karnataka' },
  { name: 'Jayanagar', district: 'Bengaluru Urban', state: 'Karnataka' },
  { name: 'HSR Layout', district: 'Bengaluru Urban', state: 'Karnataka' },
  { name: 'Electronic City', district: 'Bengaluru Urban', state: 'Karnataka' },
  { name: 'Hebbal', district: 'Bengaluru Urban', state: 'Karnataka' },
  { name: 'Yelahanka', district: 'Bengaluru Urban', state: 'Karnataka' },
  { name: 'Marathahalli', district: 'Bengaluru Urban', state: 'Karnataka' },
  { name: 'Gokulam', district: 'Mysuru', state: 'Karnataka' },
  { name: 'Jayalakshmipuram', district: 'Mysuru', state: 'Karnataka' },
  { name: 'Nanjangud', district: 'Mysuru', state: 'Karnataka' },
  { name: 'Hunsur', district: 'Mysuru', state: 'Karnataka' },
  { name: 'Vidyanagar Hubballi', district: 'Hubballi-Dharwad', state: 'Karnataka' },
  { name: 'Dharwad City', district: 'Hubballi-Dharwad', state: 'Karnataka' },
  { name: 'Kadur', district: 'Mangaluru (Dakshina Kannada)', state: 'Karnataka' },
  { name: 'Surathkal', district: 'Mangaluru (Dakshina Kannada)', state: 'Karnataka' },
  { name: 'Bantwal', district: 'Mangaluru (Dakshina Kannada)', state: 'Karnataka' },
  { name: 'Puttur', district: 'Mangaluru (Dakshina Kannada)', state: 'Karnataka' },
  { name: 'Tilakwadi', district: 'Belagavi', state: 'Karnataka' },
  { name: 'Chikkodi', district: 'Belagavi', state: 'Karnataka' },
  { name: 'Gokak', district: 'Belagavi', state: 'Karnataka' },

  // ==========================================
  // TAMIL NADU
  // ==========================================
  { name: 'T Nagar', district: 'Chennai', state: 'Tamil Nadu' },
  { name: 'Adyar', district: 'Chennai', state: 'Tamil Nadu' },
  { name: 'Anna Nagar', district: 'Chennai', state: 'Tamil Nadu' },
  { name: 'Velachery', district: 'Chennai', state: 'Tamil Nadu' },
  { name: 'Mylapore', district: 'Chennai', state: 'Tamil Nadu' },
  { name: 'Tambaram', district: 'Chennai', state: 'Tamil Nadu' },
  { name: 'Guindy', district: 'Chennai', state: 'Tamil Nadu' },
  { name: 'RS Puram', district: 'Coimbatore', state: 'Tamil Nadu' },
  { name: 'Gandhipuram', district: 'Coimbatore', state: 'Tamil Nadu' },
  { name: 'Peelamedu', district: 'Coimbatore', state: 'Tamil Nadu' },
  { name: 'Pollachi', district: 'Coimbatore', state: 'Tamil Nadu' },
  { name: 'KK Nagar Madurai', district: 'Madurai', state: 'Tamil Nadu' },
  { name: 'Anna Nagar Madurai', district: 'Madurai', state: 'Tamil Nadu' },
  { name: 'Thillai Nagar', district: 'Tiruchirappalli', state: 'Tamil Nadu' },
  { name: 'Srirangam', district: 'Tiruchirappalli', state: 'Tamil Nadu' },
  { name: 'Fairlands', district: 'Salem', state: 'Tamil Nadu' },
  { name: 'Alagapuram', district: 'Salem', state: 'Tamil Nadu' },

  // ==========================================
  // WEST BENGAL
  // ==========================================
  { name: 'Salt Lake (Bidhannagar)', district: 'Kolkata', state: 'West Bengal' },
  { name: 'New Town', district: 'Kolkata', state: 'West Bengal' },
  { name: 'Ballygunge', district: 'Kolkata', state: 'West Bengal' },
  { name: 'Alipore', district: 'Kolkata', state: 'West Bengal' },
  { name: 'Jadavpur', district: 'Kolkata', state: 'West Bengal' },
  { name: 'Behala', district: 'Kolkata', state: 'West Bengal' },
  { name: 'Dum Dum', district: 'Kolkata', state: 'West Bengal' },
  { name: 'Shibpur', district: 'Howrah', state: 'West Bengal' },
  { name: 'Bally', district: 'Howrah', state: 'West Bengal' },
  { name: 'Uluberia', district: 'Howrah', state: 'West Bengal' },
  { name: 'Barasat', district: 'North 24 Parganas', state: 'West Bengal' },
  { name: 'Barrackpore', district: 'North 24 Parganas', state: 'West Bengal' },
  { name: 'Basirhat', district: 'North 24 Parganas', state: 'West Bengal' },
  { name: 'Budge Budge', district: 'South 24 Parganas', state: 'West Bengal' },
  { name: 'Baruipur', district: 'South 24 Parganas', state: 'West Bengal' },
  { name: 'Pradhan Nagar', district: 'Siliguri', state: 'West Bengal' },
  { name: 'Matigara', district: 'Siliguri', state: 'West Bengal' },
  { name: 'Mall Road Darjeeling', district: 'Darjeeling', state: 'West Bengal' },
  { name: 'Kurseong', district: 'Darjeeling', state: 'West Bengal' },

  // ==========================================
  // ANDHRA PRADESH & TELANGANA
  // ==========================================
  { name: 'Madhapur (Hitec City)', district: 'Hyderabad', state: 'Telangana' },
  { name: 'Gachibowli', district: 'Hyderabad', state: 'Telangana' },
  { name: 'Banjara Hills', district: 'Hyderabad', state: 'Telangana' },
  { name: 'Jubilee Hills', district: 'Hyderabad', state: 'Telangana' },
  { name: 'Kukatpally', district: 'Hyderabad', state: 'Telangana' },
  { name: 'Secunderabad', district: 'Hyderabad', state: 'Telangana' },
  { name: 'Hanamkonda', district: 'Warangal', state: 'Telangana' },
  { name: 'Kazipet', district: 'Warangal', state: 'Telangana' },
  { name: 'Siricilla', district: 'Karimnagar', state: 'Telangana' },
  { name: 'Gajuwaka', district: 'Visakhapatnam', state: 'Andhra Pradesh' },
  { name: 'MVP Colony', district: 'Visakhapatnam', state: 'Andhra Pradesh' },
  { name: 'Madhurawada', district: 'Visakhapatnam', state: 'Andhra Pradesh' },
  { name: 'Benz Circle', district: 'Vijayawada', state: 'Andhra Pradesh' },
  { name: 'Governorpet', district: 'Vijayawada', state: 'Andhra Pradesh' },
  { name: 'Arundelpet', district: 'Guntur', state: 'Andhra Pradesh' },
  { name: 'Brodipet', district: 'Guntur', state: 'Andhra Pradesh' },
  { name: 'Tenali', district: 'Guntur', state: 'Andhra Pradesh' },
  { name: 'Alipiri', district: 'Tirupati', state: 'Andhra Pradesh' },
  { name: 'Renigunta', district: 'Tirupati', state: 'Andhra Pradesh' },

  // ==========================================
  // KERALA
  // ==========================================
  { name: 'Pattom', district: 'Thiruvananthapuram', state: 'Kerala' },
  { name: 'Kowdiar', district: 'Thiruvananthapuram', state: 'Kerala' },
  { name: 'Kazhakkoottam (Technopark)', district: 'Thiruvananthapuram', state: 'Kerala' },
  { name: 'Kakkanad (Infopark)', district: 'Kochi (Ernakulam)', state: 'Kerala' },
  { name: 'Palarivattom', district: 'Kochi (Ernakulam)', state: 'Kerala' },
  { name: 'Edappally', district: 'Kochi (Ernakulam)', state: 'Kerala' },
  { name: 'Fort Kochi', district: 'Kochi (Ernakulam)', state: 'Kerala' },
  { name: 'Mavoor Road', district: 'Kozhikode', state: 'Kerala' },
  { name: 'Mananchira', district: 'Kozhikode', state: 'Kerala' },

  // ==========================================
  // ODISHA
  // ==========================================
  { name: 'Saheed Nagar', district: 'Bhubaneswar', state: 'Odisha' },
  { name: 'Patia (Infocity)', district: 'Bhubaneswar', state: 'Odisha' },
  { name: 'Khandagiri', district: 'Bhubaneswar', state: 'Odisha' },
  { name: 'Badambadi', district: 'Cuttack', state: 'Odisha' },
  { name: 'CDA Sector 1-10', district: 'Cuttack', state: 'Odisha' },
  { name: 'Civil Township', district: 'Rourkela', state: 'Odisha' },
  { name: 'Grand Road', district: 'Puri', state: 'Odisha' },
  { name: 'Balighai', district: 'Puri', state: 'Odisha' },

  // ==========================================
  // JHARKHAND & CHHATTISGARH
  // ==========================================
  { name: 'Lalpur', district: 'Ranchi', state: 'Jharkhand' },
  { name: 'Doranda', district: 'Ranchi', state: 'Jharkhand' },
  { name: 'Kanke', district: 'Ranchi', state: 'Jharkhand' },
  { name: 'Bistupur', district: 'Jamshedpur (East Singhbhum)', state: 'Jharkhand' },
  { name: 'Sakchi', district: 'Jamshedpur (East Singhbhum)', state: 'Jharkhand' },
  { name: 'Bank More', district: 'Dhanbad', state: 'Jharkhand' },
  { name: 'Jharia', district: 'Dhanbad', state: 'Jharkhand' },
  { name: 'Pandri', district: 'Raipur', state: 'Chhattisgarh' },
  { name: 'Telibandha', district: 'Raipur', state: 'Chhattisgarh' },
  { name: 'Naya Raipur', district: 'Raipur', state: 'Chhattisgarh' },
  { name: 'Civic Centre', district: 'Bhilai', state: 'Chhattisgarh' },
  { name: 'Nehru Nagar Bhilai', district: 'Bhilai', state: 'Chhattisgarh' },
  { name: 'Vyapar Vihar', district: 'Bilaspur', state: 'Chhattisgarh' },

  // ==========================================
  // ASSAM & NORTH EAST
  // ==========================================
  { name: 'Dispur', district: 'Guwahati (Kamrup Metropolitan)', state: 'Assam' },
  { name: 'Paltan Bazaar', district: 'Guwahati (Kamrup Metropolitan)', state: 'Assam' },
  { name: 'Ganeshguri', district: 'Guwahati (Kamrup Metropolitan)', state: 'Assam' },
  { name: 'Jalukbari', district: 'Guwahati (Kamrup Metropolitan)', state: 'Assam' },
  { name: 'Rongpur', district: 'Silchar', state: 'Assam' },
  { name: 'Tarapur', district: 'Silchar', state: 'Assam' },
  { name: 'Boiragimoth', district: 'Dibrugarh', state: 'Assam' },
  { name: 'Agartala Central', district: 'West Tripura', state: 'Tripura' },
  { name: 'Police Bazar', district: 'East Khasi Hills (Shillong)', state: 'Meghalaya' },
  { name: 'Laban', district: 'East Khasi Hills (Shillong)', state: 'Meghalaya' },
  { name: 'Imphal Bazar', district: 'Imphal West', state: 'Manipur' },
  { name: 'Khatla', district: 'Aizawl', state: 'Mizoram' },
  { name: 'Kohima Village', district: 'Kohima', state: 'Nagaland' },
  { name: 'Dimapur Town', district: 'Dimapur', state: 'Nagaland' },
  { name: 'Ganga Market', district: 'Papum Pare (Itanagar)', state: 'Arunachal Pradesh' },
  { name: 'MG Marg Gangtok', district: 'Gangtok', state: 'Sikkim' },

  // ==========================================
  // UTTARAKHAND & HIMACHAL PRADESH
  // ==========================================
  { name: 'Rajpur Road', district: 'Dehradun', state: 'Uttarakhand' },
  { name: 'Jakhan', district: 'Dehradun', state: 'Uttarakhand' },
  { name: 'Clement Town', district: 'Dehradun', state: 'Uttarakhand' },
  { name: 'Rishikesh Town', district: 'Dehradun', state: 'Uttarakhand' },
  { name: 'Jawlapur', district: 'Haridwar', state: 'Uttarakhand' },
  { name: 'Kankhal', district: 'Haridwar', state: 'Uttarakhand' },
  { name: 'Civil Lines Roorkee', district: 'Haridwar', state: 'Uttarakhand' },
  { name: 'Tallital', district: 'Nainital', state: 'Uttarakhand' },
  { name: 'Mallital', district: 'Nainital', state: 'Uttarakhand' },
  { name: 'Haldwani Market', district: 'Nainital', state: 'Uttarakhand' },
  { name: 'The Mall Shimla', district: 'Shimla', state: 'Himachal Pradesh' },
  { name: 'Sanjauli', district: 'Shimla', state: 'Himachal Pradesh' },
  { name: 'Chotta Shimla', district: 'Shimla', state: 'Himachal Pradesh' },
  { name: 'Kotwali Bazar', district: 'Kangra (Dharamshala)', state: 'Himachal Pradesh' },
  { name: 'McLeod Ganj', district: 'Kangra (Dharamshala)', state: 'Himachal Pradesh' },
  { name: 'Mall Road Manali', district: 'Kullu', state: 'Himachal Pradesh' },
  { name: 'Dhalpur', district: 'Kullu', state: 'Himachal Pradesh' },
  { name: 'Chambaghat', district: 'Solan', state: 'Himachal Pradesh' },

  // ==========================================
  // JAMMU & KASHMIR, LADAKH, GOA & UTs
  // ==========================================
  { name: 'Lal Chowk', district: 'Srinagar', state: 'Jammu and Kashmir' },
  { name: 'Rajbagh', district: 'Srinagar', state: 'Jammu and Kashmir' },
  { name: 'Hazratbal', district: 'Srinagar', state: 'Jammu and Kashmir' },
  { name: 'Gandhi Nagar Jammu', district: 'Jammu', state: 'Jammu and Kashmir' },
  { name: 'Bahu Plaza', district: 'Jammu', state: 'Jammu and Kashmir' },
  { name: 'Main Bazar Leh', district: 'Leh Ladakh', state: 'Ladakh' },
  { name: 'Choglamsar', district: 'Leh Ladakh', state: 'Ladakh' },
  { name: 'Miramar', district: 'North Goa', state: 'Goa' },
  { name: 'Panaji Market', district: 'North Goa', state: 'Goa' },
  { name: 'Calangute', district: 'North Goa', state: 'Goa' },
  { name: 'Candolim', district: 'North Goa', state: 'Goa' },
  { name: 'Mapusa Town', district: 'North Goa', state: 'Goa' },
  { name: 'Margao Market', district: 'South Goa', state: 'Goa' },
  { name: 'Vasco Da Gama', district: 'South Goa', state: 'Goa' },
  { name: 'Colva', district: 'South Goa', state: 'Goa' },
  { name: 'Ponda Town', district: 'South Goa', state: 'Goa' },
  { name: 'Silvassa City', district: 'Dadra and Nagar Haveli', state: 'Dadra and Nagar Haveli and Daman and Diu' },
  { name: 'Naroli', district: 'Dadra and Nagar Haveli', state: 'Dadra and Nagar Haveli and Daman and Diu' },
  { name: 'Nani Daman', district: 'Daman', state: 'Dadra and Nagar Haveli and Daman and Diu' },
  { name: 'Moti Daman', district: 'Daman', state: 'Dadra and Nagar Haveli and Daman and Diu' },
  { name: 'Ghoghla', district: 'Diu', state: 'Dadra and Nagar Haveli and Daman and Diu' },
  { name: 'Sector 17 Chandigarh', district: 'Chandigarh', state: 'Chandigarh' },
  { name: 'Sector 35 Chandigarh', district: 'Chandigarh', state: 'Chandigarh' },
  { name: 'Manimajra', district: 'Chandigarh', state: 'Chandigarh' },
  { name: 'White Town', district: 'Puducherry', state: 'Puducherry' },
  { name: 'Auroville Area', district: 'Puducherry', state: 'Puducherry' },
  { name: 'Oulgaret', district: 'Puducherry', state: 'Puducherry' },
  { name: 'Aberdeen Bazaar', district: 'South Andaman (Port Blair)', state: 'Andaman and Nicobar Islands' },
  { name: 'Garacharma', district: 'South Andaman (Port Blair)', state: 'Andaman and Nicobar Islands' },
  { name: 'Kavaratti Town', district: 'Lakshadweep', state: 'Lakshadweep' },
]

// To ensure EVERY single district in every state has at least fallback prominent rural/urban villages/areas:
// We iterate through all districts in all_india_cities.json. If a district has no explicit village above,
// we generate standard prominent rural taluka/block/area entries for it so users always get meaningful suggestions!
const knownDistrictsWithVillages = new Set(
  VILLAGES_DATA.map((v) => `${(v.state || '').toLowerCase()}|${(v.district || '').toLowerCase()}`)
)

citiesData.forEach((cityObj) => {
  const key = `${(cityObj.state || '').toLowerCase()}|${(cityObj.name || '').toLowerCase()}`
  if (!knownDistrictsWithVillages.has(key)) {
    // Add primary Tehsil / Block / Rural Area for this district
    VILLAGES_DATA.push(
      {
        name: `${cityObj.name} Rural Area`,
        district: cityObj.name,
        state: cityObj.state,
      },
      {
        name: `${cityObj.name} Main Town`,
        district: cityObj.name,
        state: cityObj.state,
      },
      {
        name: `${cityObj.name} Tehsil / Block`,
        district: cityObj.name,
        state: cityObj.state,
      }
    )
  }
})

// Sort villages alphabetically by state -> district -> name
VILLAGES_DATA.sort((a, b) => {
  if (a.state !== b.state) return a.state.localeCompare(b.state)
  if (a.district !== b.district) return a.district.localeCompare(b.district)
  return a.name.localeCompare(b.name)
})

const outputPath = path.join(__dirname, '../src/data/all_india_villages.json')
fs.writeFileSync(outputPath, JSON.stringify(VILLAGES_DATA, null, 2), 'utf8')

// console.log(`Generated all_india_villages.json with ${VILLAGES_DATA.length} entries across all states!`)
